### PR TITLE
[MM-56058] Build and release multi-arch docker images

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR introduces multi-arch support to our docker builds through `docker buildx`. This will allow us to run these containers on different instance architectures (e.g. AWS Graviton) that showed good improvements at reduced cost during testing.

I am starting from `calls-recorder` since it's probably the trickiest of the three repositories to port. (`calls-offloader` and `calls-transcriber` being the others). If this is approved I'll go ahead with the rest of them.

To make these changes I have been roughly following https://docs.docker.com/build/guide/multi-platform/.

One caveat with the recommended approach is that it doesn't really allow to have shasums in the image since dockerfiles are dynamically built based on the target platform. I am hoping this not to be a blocking issue especially considering that it's been a bit of a pain to keep everything up to date. Also we are still pinning by version both on the Golang builder and debian runner image.

@phoinixgrr Adding you in case you have any suggestions. I am hoping that once https://github.com/mattermost/delivery-platform/pull/67 is merged this will work without too much troubles.

@cpoile This should also take care of local builds on arm64 based systems. Give it a try and let me know if you run into any issues.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-56058

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Works on m1 using `make docker-build`, no need to pin new packages. Thanks!

**Comment by iyampaul** [comment]
> LGTM, but let's get a comment from @esarafianou and/or @iyampaul on the shasum issue.

Wasn't the intent already to use cosign to sign the docker images? Unless I'm messing something, If we can validate the sig and pin the version we should be ok?

**Comment by streamer45** [comment]
@iyampaul This change is purely about base images we depend on (namely Golang and Debian) which are still pinned by version but with the specific shasum removed since the actual image would be dynamic based on the platform. Nothing changes to our signing and verification process once the final image is built.

**Comment by iyampaul** [comment]
> @iyampaul This change is purely about base images we depend on (namely Golang and Debian) which are still pinned by version but with the specific shasum removed since the actual image would be dynamic based on the platform. Nothing changes to our signing and verification process once the final image is built.

Got it.  From our convo on Friday and review, without substantial change to the process it will be difficult to collect + use the shasum's to validate the base images coming from Docker Hub.  We should be enforcing `--tlsverify` so we can (in the least) positively confirm the connection with Docker Hub when we are pulling the base images, so there isn't risk of the Actions runners hitting another image source.

**Comment by streamer45** [comment]
Thanks @iyampaul. I'd totally expect Docker to default to TLS for any request to the public registry which is what we'd be using here for pulling base images. The [`--tlsverify`](https://docs.docker.com/engine/security/protect-access/#client-modes) flag seems mostly about TLS communication with the docker socket or to private registries and that will require a valid CA to be passed. Is that really what we need here?

**Comment by esarafianou** [comment]
@streamer45 just FYI I removed the request from my review. If both Paul and Juho are ok with the change, I'm not needed to review.

**Review by iyampaul — APPROVED** [review]

**Comment by streamer45** [comment]
@cpoile We have our first official multiarch dev images :tada:

https://hub.docker.com/layers/mattermost/calls-recorder/v0.7.0-dev1/images/sha256-d6d46811776217a9c5a3692225e153cc17ff6a44cb1765a5a5f65a5c8a73046d?context=explore

I'll test them out a bit and if positive will proceed to add support to the rest of our docker releases (i.e. offloader and transcriber)

**Pull request merged**
